### ISSUE TITLE
Using external SQL server

### ISSUE THREAD

**Issue by cloudlady911** [sshipway/Portus#6]
I would like to use a mysql server I already have.

Can I modify these settings like this? (Not sure about the port setting) and remove the link to the db container?

```
PORTUS_PRODUCTION_DATABASE: portus
PORTUS_PRODUCTION_HOST: databasehostname:3306
PORTUS_PRODUCTION_PASSWORD: SOMEPASSWORD
PORTUS_PRODUCTION_USERNAME: portus
```

**Comment by sshipway** [comment]
Yes, this should work.  Mysql is port 3306 by default unless you changed the port.
